Enable travis-ci
datenlord/datenlord pull request #121
Opened 2020-10-08 12:59 UTC by Nugine

This pr adds 6 checks:

|arch|os|rust|
|-|-|-|
|AMD64|ubuntu 16.04|stable|
|Arm64|ubuntu 16.04|stable|
|AMD64|macOS 10.13|stable|
|AMD64|ubuntu 16.04|nightly|
|Arm64|ubuntu 16.04|nightly|
|AMD64|macOS 10.13|nightly|

References:

1. <https://docs.travis-ci.com/user/languages/rust/>
2. <https://docs.travis-ci.com/user/reference/linux/>
3. <https://docs.travis-ci.com/user/reference/osx/>

2020-10-08 13:53 UTC, Nugine commented
Travis CI failed because of mismatched types. (compile error)
See <https://travis-ci.com/github/datenlord/datenlord/jobs/396944281>

2020-10-11 13:34 UTC, pwang7 requested changes

2020-10-11 13:34 UTC, pwang7 commented on .github/workflows/ci.yml
> +  CI_RUST_TOOLCHAIN: stable
let's fix it to 1.46 for now

2020-10-11 14:04 UTC, Nugine commented on .github/workflows/ci.yml
> +  CI_RUST_TOOLCHAIN: stable
Ok

2020-10-12 02:21 UTC, Nugine commented
Travis CI failed on arm64.
GitHub CI failed on macos.
Waiting for the master branch to fix.

2020-10-13 10:07 UTC, Nugine commented
ready to merge

2020-10-15 15:17 UTC, Nugine commented
Clippy still failed on macOS.
Waiting for the master branch to fix.

2020-10-15 17:01 UTC, pwang7 approved these changes

2020-10-15 17:02 UTC, merged