Add monitoring and logging to datenlord
datenlord/datenlord pull request #206
Opened 2021-05-29 22:28 UTC by mrwwheat7

2021-06-06 02:34 UTC, pzheng1025 commented on scripts/datenlord-deploy.sh
> +else
define a valid value for $1?

2021-06-08 00:31 UTC, pzheng1025 commented on scripts/datenlord-deploy.sh
> +fi
Maybe change the name of this script to deploy-monitoring or others. It doesn't deploy DatenLord.

2021-07-07 16:09 UTC, pwang7 requested changes

2021-07-07 16:09 UTC, pwang7 commented on scripts/datenlord-monitor.yaml
> +      nodePort: 32000
add extra empty line

2021-07-07 16:09 UTC, pwang7 commented on scripts/datenlord-monitor-deploy.sh
> +fi
add extra empty line

2021-07-07 16:09 UTC, pwang7 commented on scripts/Datenlord_Dashboard.json
> +}
add extra empty line

2021-07-07 16:09 UTC, pwang7 commented on .github/workflows/cron.yml
> +  MINIKUBE_VERSION: v1.13.0
comment out minikube version, since we don't use it

2021-07-11 05:18 UTC, mrwwheat7 reviewed
Add test for AlertManager

2021-07-18 05:03 UTC, mrwwheat7 commented on scripts/datenlord-monitor-deploy.sh
> +    kubectl wait --for=condition=Ready pod -l app.kubernetes.io/name=grafana -n datenlord-monitoring --timeout=60s
Add status check for promethues

2021-07-18 05:07 UTC, mrwwheat7 reviewed
Remove data origin for promethues

2021-07-18 05:08 UTC, mrwwheat7 commented on scripts/datenlord-monitor-deploy.sh
> +    kubectl port-forward $POD_NAME 3000 -n datenlord-monitoring
Make the port as env variable

2021-07-18 05:10 UTC, mrwwheat7 commented on .github/workflows/cron.yml
> +          kubectl apply -f $DATENLORD_MONITORING
Change it to datenlord-monitoring-deploy.sh

2021-07-18 05:26 UTC, mrwwheat7 commented on scripts/datenlord-monitor.yaml
> +          - "alertmanager.datenlord-monitoring.svc:8080"
Extract static configs to another ConfigMap, and dynamically config it.

2021-08-08 23:39 UTC, pzheng1025 commented on .github/workflows/cron.yml
> +          test -n #FOUND_PATH || (echo "FAILED TO FIND PROMETHEUS SERVICE" && /bin/false)
$FOUND_PATH ?

2021-08-15 01:20 UTC, pzheng1025 commented on scripts/values.yaml
> +---
Could you change the file name to give more information? like xxx_value.yaml?

2021-08-21 23:25 UTC, pzheng1025 approved these changes

2021-08-23 03:39 UTC, pwang7 approved these changes

2021-08-23 03:39 UTC, merged