Fix csi bug. Select node from accessibility requirements if any.
datenlord/datenlord pull request #210
Opened 2021-06-13 06:56 UTC by pzheng1025

2021-06-13 12:52 UTC, pwang7 requested changes

2021-06-13 12:52 UTC, pwang7 commented on csi/src/meta_data.rs
> +    /// Validate if a node exists in topology
add empty line before comments

2021-06-13 12:52 UTC, pwang7 commented on csi/src/meta_data.rs
> +    /// Validate if a node exists in accessibility requirements
add empty line before comments

2021-06-13 12:52 UTC, pwang7 commented on csi/src/meta_data.rs
>      /// Select a node to create volume or snapshot
add empty line before comments

2021-06-13 15:56 UTC, pzheng1025 commented on csi/src/meta_data.rs
> +    /// Validate if a node exists in topology
Done

2021-06-13 15:56 UTC, pzheng1025 commented on csi/src/meta_data.rs
> +    /// Validate if a node exists in accessibility requirements
Done

2021-06-13 15:56 UTC, pzheng1025 commented on csi/src/meta_data.rs
>      /// Select a node to create volume or snapshot
Done

2021-06-14 02:02 UTC, pwang7 approved these changes

2021-06-14 02:02 UTC, merged