feat: init ring implement.
datenlord/datenlord pull request #506
Opened 2024-03-22 10:37 UTC by IRONICBo

Implement a simpe consistant hash ring by `range` array, support balance and expand.

```rs
```

2024-03-26 05:56 UTC, frostyplanet commented
pub fn get_nodes() 函数没看懂， 什么情况下会一个 key 对应多个 node? 用在什么地方

2024-03-26 06:37 UTC, frostyplanet commented
由于 meta client 的文件现在还没实现，我觉得 MetaClient 这个  trait 的接口定义得不是很实用.
应该只需要定以下几个接口：
* register()  节点上线注册
* watch() 等待节点上下线事件的通知
* save_ring() 保存
* load_ring() 加载

2024-03-26 06:45 UTC, frostyplanet commented
1. 目前应该没有 replicas 的需求，所以这部分函数应该不用实现
2. pub fn get_nodes() 函数没看懂， 什么情况下会一个 key 对应多个 node? 用在什么地方
3. 对于 Node, id 有什么意义，id 由谁分配？如何取值
4. 灵魂问题：slot 有什么存在的必要。
现在看这个实现 rebalance 是给各个node 等分， slot 和 node 是一一对应的关系，那么 就没有 slot这个概念存在的必要。 
假如是用一致性 hash的做法， 那么 一个 node 就可能对应 多个 slot(vnode)。
初始化 capacity 默认 1024也没必要, 直接把 capacity 等于 u64 最大值 就不需要 expand了。

2024-03-26 06:47 UTC, frostyplanet requested changes

2024-03-26 06:47 UTC, frostyplanet commented on src/storage/cache_proxy/ring.rs
> +        while usize_to_u64(self.slots.len()) >= thres && must {
这个地方不是循环没必要用 while吧？

2024-03-26 06:47 UTC, frostyplanet commented on src/storage/cache_proxy/ring.rs
> +        if must && !self.rebalance() {
rebalance 应该不存在 fail 的情况， 既然节点已经加进去了, 就肯定不是 empty

2024-03-26 06:55 UTC, frostyplanet requested changes

2024-03-26 06:55 UTC, frostyplanet commented on Cargo.toml
> +siphasher = "0.3.1"
Better not introduce new dependency, unless it's a "must".
There are too many hasher out there, need throughout investigate to pick one

2024-04-02 10:14 UTC, frostyplanet commented
the change in the latest commit "[feat: Update meta client.](https://github.com/datenlord/datenlord/pull/506/commits/cc589d45f1d7ef772f08164e9fba439a47c90cc8)"
should be split apart.  

Those fix the previous commit better be merged with the previous commits.

Unfinished commented code  better not submit now,  or mark the commit as "temp" to indicate it will be rewrite later

2024-04-09 10:49 UTC, IRONICBo commented
> the change in the latest commit "[feat: Update meta client.](https://github.com/datenlord/datenlord/pull/506/commits/cc589d45f1d7ef772f08164e9fba439a47c90cc8)" should be split apart.
> 
> Those fix the previous commit better be merged with the previous commits.
> 
> Unfinished commented code better not submit now, or mark the commit as "temp" to indicate it will be rewrite later

Etcd part has moved to https://github.com/datenlord/datenlord/pull/514

2024-04-17 07:46 UTC, merged