feat: support hash ring etcd
datenlord/datenlord pull request #514
Opened 2024-04-09 10:48 UTC by IRONICBo

Support distribute cache meta engine type: etcd.

1. Use kvengine as common client.
2. Support watch function(TODO)
3. Implement basic `MetaDataClient` trait.

2024-04-24 10:58 UTC, frostyplanet requested changes

2024-04-24 10:58 UTC, frostyplanet commented on src/storage/cache_proxy/cluster_informer.rs
> +                    // Retry to keep alive node
Either remove or implement this commented code

2024-04-24 10:58 UTC, frostyplanet commented on src/storage/cache_proxy/cluster_informer.rs
> +                let value_key = &KeyType::CacheNodeMaster("/".to_string());
Should use a prefix instead of "/",  since watch has better behavior under a prefix

2024-05-07 09:58 UTC, IRONICBo commented
Etcd value.
```bash
CacheNode192.168.1.2
{"Json":{"ip":"192.168.1.2","port":0,"status":"Initializing","weight":0}}
CacheNode192.168.1.3
{"Json":{"ip":"192.168.1.3","port":0,"status":"Initializing","weight":0}}
CacheNode192.168.1.4
{"Json":{"ip":"192.168.1.4","port":0,"status":"Initializing","weight":0}}
CacheNodeMaster
{"Json":{"hash_ring_version":1,"node_ip":"192.168.1.2","node_port":0}}
```

Election logs.
```bash
   Compiling datenlord v0.1.0 (/data/test_download/datenlord)
    Finished test [unoptimized + debuginfo] target(s) in 2m 16s
     Running unittests src/main.rs (target/debug/deps/datenlord-c9bb3d8e03781f53)

running 1 test
2024-05-07T07:47:28.196011Z  INFO datenlord::storage::cache_proxy::cluster_manager::tests: test_single_master_election: start to test single master election
2024-05-07T07:47:28.196098Z  INFO datenlord::storage::cache_proxy::cluster_manager: register: 192.168.1.2 to etcd
2024-05-07T07:47:28.199493Z  INFO datenlord::storage::cache_proxy::cluster_manager: register: 192.168.1.2 to etcd success
2024-05-07T07:47:28.200624Z  INFO datenlord::async_fuse::memfs::kv_engine::etcd_impl: keep alive lease, lease_id=7587878528924386919
2024-05-07T07:47:28.203539Z  INFO datenlord::async_fuse::memfs::kv_engine::etcd_impl: campaign success, key=CacheNodeMaster, val=Json(Object {"hash_ring_version": Number(1), "node_ip": String("192.168.1.2"), "node_port": Number(0)})
2024-05-07T07:47:28.205300Z  INFO datenlord::async_fuse::memfs::kv_engine::etcd_impl: keep alive lease, lease_id=7587878528924386922
2024-05-07T07:47:33.198298Z  INFO datenlord::storage::cache_proxy::cluster_manager: register: 192.168.1.3 to etcd
2024-05-07T07:47:33.198474Z  INFO datenlord::storage::cache_proxy::cluster_manager: register: 192.168.1.4 to etcd
2024-05-07T07:47:33.201822Z  INFO datenlord::storage::cache_proxy::cluster_manager: register: 192.168.1.3 to etcd success
2024-05-07T07:47:33.203275Z  INFO datenlord::storage::cache_proxy::cluster_manager: register: 192.168.1.4 to etcd success
2024-05-07T07:47:33.204393Z  INFO datenlord::async_fuse::memfs::kv_engine::etcd_impl: keep alive lease, lease_id=7587878528924386926
2024-05-07T07:47:33.205327Z  INFO datenlord::async_fuse::memfs::kv_engine::etcd_impl: keep alive lease, lease_id=7587878528924386928
2024-05-07T07:47:33.206091Z  INFO datenlord::async_fuse::memfs::kv_engine::etcd_impl: campaign failed, key=CacheNodeMaster, val=Json(Object {"hash_ring_version": Number(1), "node_ip": String("192.168.1.3"), "node_port": Number(0)})
2024-05-07T07:47:33.206988Z  INFO datenlord::async_fuse::memfs::kv_engine::etcd_impl: campaign failed, key=CacheNodeMaster, val=Json(Object {"hash_ring_version": Number(1), "node_ip": String("192.168.1.4"), "node_port": Number(0)})
2024-05-07T07:47:33.207037Z  INFO datenlord::storage::cache_proxy::cluster_manager::tests: test_single_master_election: finish to test single master election
2024-05-07T07:47:33.207052Z  INFO datenlord::storage::cache_proxy::cluster_manager::tests: Master node status: Master
2024-05-07T07:47:33.207065Z  INFO datenlord::storage::cache_proxy::cluster_manager::tests: Slave node 1 status: Slave
2024-05-07T07:47:33.207078Z  INFO datenlord::storage::cache_proxy::cluster_manager::tests: Slave node 2 status: Slave
test storage::cache_proxy::cluster_manager::tests::test_single_master_election ... ok
```

2024-06-05 10:57 UTC, frostyplanet commented
Should base on #520 and reuse Session from KvEngine

2024-06-26 06:58 UTC, closed without merging